/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContainerBar: typeof import('./src/components/container/ContainerBar.vue')['default']
    ContainerCol1: typeof import('./src/components/container/ContainerCol1.vue')['default']
    ContainerCol2: typeof import('./src/components/container/ContainerCol2.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RiFolderFill: typeof import('@remixicon/vue')['RiFolderFill']
    RiHomeFill: typeof import('@remixicon/vue')['RiHomeFill']
    RiMessage3Fill: typeof import('@remixicon/vue')['RiMessage3Fill']
    RiSettingsFill: typeof import('@remixicon/vue')['RiSettingsFill']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
